# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQTwZFLalB_Yq3Ig2QllP6cAOCZJiVo9
"""

#sum of two numbers
a=int(input("Enter the first number: "))
b=int(input("Enter the second number: "))
c=a+b
print("Sum of two numbers is: ",c)

# area of circle
r=int(input("Enter the value of radius of circle "))
#area=3.14*r*r
area=3.14*r**2
print("area of circle is: ",area)

#area of rectangle
l=int(input("Enter length: "))
b=int(input("Enter breadth: "))
print("Area of rectangle is",l*b)

#Calculator
x=int(input("Enter first value: "))
y=int(input("Enter second value: "))

sum=x+y
diff=x-y
mult=x*y
div=int(x/y)

print("Sum is: ",sum)
print("Difference is: ",diff)
print("Product is: ", mult)
print("Quotient is: ",div)

#volume of a cube
r=int(input("Enter value of side of cube "))
vol=r**3
print("Volume of cube with radius",r,"is: ",vol)

#temperature conversion
t=int(input("Enter the temperature in Kelvin "))
T=(t-32)*(5/9)
print("Temperature in kelvin is: ",T)

#Day 2:  Conditional statement
#IF ELSE condition
#If number positive or not
n=int(input("Enter a number "))
if(n>0):
  print("Number is POSITIVE")
else:
  print("NEGATIVE")

#With zero
n=int(input("Enter a number "))
if(n>0):
  print("Number is POSITIVE")
elif(n<0):
  print("NEGATIVE")
else:
  print("Zero")

#Even or odd
n=int(input("Enter a number "))
rem=n%2 #remainder is returned
if(rem==0):
  print("EVEN")
else:
  print("ODD")

#Pass or fail
mark=int(input("Enter your marks in 100 "))
if(mark>=40):
  print("PASS")
else:
  print("FAIL")

#Greatest of 2 numbers
a=int(input("Enter 1st value: "))
b=int(input("Enter 2nd value: "))
if(a>b):
  print("First number if greater")
else:
  print("Second number if greater")

#Exp-1
#Prog-1: add n numbers
a=int(input("Enter a number "))
#if a<0:
#  print("Enter a positive number ")
sum=0
while (a>0):
  sum+=a
  a-=1
print("Sum is: ",sum)

#Exp-1
#Prog-2: largest number among three numbers
n1=int(input("Enter 1st no. "))
n2=int(input("Enter 2nd no. "))
n3=int(input("Enter 3rd no. "))
if n1>n2 and n1>n3:
  n=n1
elif n2>n1 and n2>n3:
  n=n2
else:
  n=n3
print(n," is the greatest")