# -*- coding: utf-8 -*-
"""Day 5-list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13OFR8pJThp1S6nB88qs5id3QjrYCLCVC

Day 10: Lists
square brackets
non homogeneous (not similar data types) can be stored in list
"""

list1=[1,2.7,"good morning"]
list2=[] #empty list
list3=[3, 5.6,list1]
print(type(list1))
print(type(list2))
print(type(list3))

list1=[1,2.7,"good morning"]
list2=[3, 5.6,list1]
list3=list1+list2
list4=list1*4
print(list3)
print(list4)

#list indexing
fruit_list=['Grapes','banana','apple','guava','orange']
print(fruit_list[0])
print(fruit_list[-1])
print(len(fruit_list))

#List Slicing
fruit_list=['Grapes','banana','apple','guava','orange']
print(fruit_list[0:4])
print(fruit_list[0:4:2])
print(fruit_list[::-1])
print(fruit_list[0::-1])
print(fruit_list[1::-1])

#looping through a list
list1=[1.2,3.5,6,8.4]
sum=0
for i in list1:
  sum+=i
print("Sum is",sum)

fruit_list=['Grapes','banana','apple','guava','orange']
for i in fruit_list:
  print(i.upper())

#insertion [append, insert, extend]
list1=[1,2,3]
n=int(input("Enter a value to be added in list "))
list1.append(n)
print(list1)

list1=[1,2,3]
n=int(input("Enter a value to be added in list "))
#list1.insert(-1,n) #2 arguments of insert function: position and value to be inserted
list1.insert(0,n)
print(list1)

list1=[1,2,3]
list2=[4.5,5.6, 7.8]
list1.extend(list2)
print(list1)

#remove values from list - pop, remove,del
list1 =[1,2,3,4,5,6]
list1.pop() #by default will remove last item
print(list1)

list1 =[1,2,3,4,5,6]
list1.pop(3)#removes item from a particular position
print(list1)

list1 =[1,2,3,4,5,6]
list1.pop(-1)
print(list1)

#remove - takes item and not its position
fruit_list=['Grapes','banana','apple','guava','orange']
fruit_list.remove('Grapes')
print(fruit_list)

#del- string slicing can be applied
fruit_list=['Grapes','banana','apple','guava','orange']
del fruit_list[0]
print(fruit_list)

fruit_list=['Grapes','banana','apple','guava','orange']
del fruit_list[0:2]
print(fruit_list)

#clear
fruit_list=['Grapes','banana','apple','guava','orange']
fruit_list.clear()
print(fruit_list)

#copying a list
a='apple'
b=a
a='APPLE'
print(a)
print(b)

a=[1,2,3]
b=a
a.append(5)#in string no change when copied. but in list, both original and copy are changed
print(a)
print(b)

a=[1,2,3]
b=a.copy()#when a copy of a is stored in b, then change in a will not be reflected in b
a.append(5)
print(a)
print(b)

